### PR TITLE
Convert to a NPM package

### PR DESCRIPTION
**Pull request by ldez**
Hello,

I have add all elements to publish a [NPM](https://www.npmjs.com/) package and more...

- [NPM](https://www.npmjs.com/) configuration
- add tests
- add build system
- add EditorConfig
- add Coffeelint
- add basic [TravisCI](https://travis-ci.org) configuration

How to use:
- `npm run build` -> build JS files
- `npm run test` -> run all tests (one shot)
- `npm run test:auto` -> run all tests ans watch change
- `npm publish` -> publish package to [NPM](https://www.npmjs.com/)

### CODE REVIEW

**Comment by akheron** [comment]
Hey! I have very little time for this project anymore, so would you like to have push access?

**Comment by ldez** [comment]
@akheron yes, I'm interested in having push access.
Will you allow me to publish on NPM too?

**Comment by akheron** [comment]
I could actually transfer the whole repo to you so we don't need to deal with npm. But you have to remove your fork first. I merged this PR so it's now possible to delete it without losing anything.

**Comment by ldez** [comment]
I have suppressed my fork.

**Comment by akheron** [comment]
Transfer request sent.

**Comment by ldez** [comment]
Thank you.

**Pull request merged**
